[package]
name = "storage-engine"
version = "0.1.0"
edition = "2024"

[lib]
name = "storage_engine"
path = "src/lib.rs"

[dependencies]
squirrel_core = { path = "../core", package = "core" }
meta_service = { path = "../meta-service", package = "meta-service" }