[package]
name = "core"
version = "0.1.0"
edition = "2024"

[lib]
name = "core"
path = "src/lib.rs"


[dependencies]
rust_decimal = "1.37.1"
serde_json = "1.0.140"
serde = { version = "1.0", features = ["derive"] }
